#!/bin/bash

qemu_args=()
while [[ "$1" != "" ]]
do
    case "$1" in
    -Wq,*) qemu_args+=("${1#-Wq,}"); shift;;
    *) break;;
    esac
    shift
done

xlen="$(readelf -h $1 | sed -n 's/^ *Class: *ELF//p')"
xlen=$(readelf -h $1)
xlen=${xlen% Data: *}
xlen=${xlen##*ELF}

QEMU_CPU=${QEMU_CPU} qemu-riscv$xlen -r 5.10 "${qemu_args[@]}" -L ${RISC_V_SYSROOT} "$@"
